ARG ELIXIR_VERSION=1.18.3
ARG OTP_VERSION=27
ARG MIX_ENV=prod
ARG IMAGE=elixir:${ELIXIR_VERSION}-otp-${OTP_VERSION}-slim

# BUILD

FROM ${IMAGE} AS builder

RUN apt-get update -y && apt-get install ca-certificates -y
RUN apt-get clean && rm -f /var/lib/apt/lists/*_*

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV}

WORKDIR /app

COPY mix.exs ./
COPY mix.lock ./
COPY config ./config
COPY lib ./lib

RUN mix deps.get
RUN mix compile

COPY rel rel

RUN mix release

# RUNTIME

FROM ${IMAGE} AS runner

RUN apt-get update -y && apt-get install ca-certificates curl jq -y
RUN apt-get clean && rm -f /var/lib/apt/lists/*_*
WORKDIR /app

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV}

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY --from=builder /app/_build/${MIX_ENV}/rel/cluster_demo ./

CMD ["/app/bin/cluster_demo", "start"]


